### ISSUE TITLE
Add album to play next/play later.

### ISSUE THREAD

**Issue by drasbeck** [zachomedia/apple-music-webplayer#102]
I have not been able to figure out how to add an entire album to play next/play later, like we can do with single tracks by pressing the horizontal hamburger menu on an album page. Feel free to close this issue, if I'm just to blind to see it, but:

Please consider implementing the feature of adding an entire album to play next/play later.

**Comment by zachomedia** [comment]
@drasbeck You didn't missing anything, it wasn't available as an option. I have now added to ability to play an entire album next or later

Thanks for the request!

**Comment by drasbeck** [comment]
Now _that's_ a quick turnaround for an issue. :D Thanks a lot!

One note to add, while the _play next/play later_ buttons work very well, as long as the _up next_ list is **not** empty, they do not seem to work when the list **is** empty. It would make sense if they would just queue the album, regardless of _up next_ list length.

**Comment by zachomedia** [comment]
You're welcome! 

I noticed that as well and unfortunately that is all controlled by MusicKit JS, so I will have to open a bug report with them to hopefully fix that behaviour.
