### ISSUE TITLE
LOAD MORE SONGS-ALBUMS!!!

### ISSUE THREAD

**Issue by PANOSmma** [zachomedia/apple-music-webplayer#105]
MY FRIEND TELL ME PLEASE YOU WILL MAKE IT LAOD MORE SONGS AND ALBUMS...ABOUT 200-300?TELL ME PLEASE THAT YOU WILL DO IT!!!HAPPH AND BLESSED NEW YEAR!!!!

**Comment by zachomedia** [comment]
@PANOSmma All of the songs / albums / etc. are loaded at the maximum per request that Apple permits through its APIs.

I just changed the search to load the maximum permitted of 25 per request.

**Comment by PANOSmma** [comment]
WOOWWWWWWWW THANKS SO MUCHHHHHHHHHHH....IS MUCH BETTER.BUT REALLY YOU CANT
LOAD MORE THAN 25 AT LEAST 100???

Στις Δευ, 6 Ιαν 2020 στις 5:38 π.μ., ο/η Zachary Seguin <
notifications@github.com> έγραψε:

**Comment by PANOSmma** [comment]
MY GOOD FRIEND SOMETHING MORE PLEASE!!!I AM BEGGING YOU CAN YOU MAKE A
ADVANCED SEARCH TO FIND MUSIC ON YOUR UNBELIEVABLE WEB AND DESIGN SONGS AND
ALBUMS BY DATE AND BY GENRE?THIS MAKE ME SOOOOOOOOOOOOOOOOO
HAPPYYYYYYYYYYYYYYY....PLEASE DUDEEEEEEEEE...AS PROGRAMMER I BELIEVE YOU
CAN!!!PLEASEEEEEEEEEEE MANNNNNNNNNNNN

Στις Δευ, 6 Ιαν 2020 στις 10:04 π.μ., ο/η panos panukos <
greciiiiaaa1982@gmail.com> έγραψε:
