### ISSUE TITLE
Play and pause icon width causes shaky top bar

### ISSUE THREAD

**Issue by ashtoncowie** [zachomedia/apple-music-webplayer#115]
The icons for play and pause seem to have a mask with very slight difference in width, which causes every UI element on the top playback bar to "shake" when a quick transition between the two occurs. This is a minor aesthetic issue but I figured I'd submit it :)

**Comment by zachomedia** [comment]
Thanks 🙂 I'll see that these be made the same width to prevent this

**Comment by zachomedia** [comment]
This has now been implemented! Thanks for the report 🙂
