### ISSUE TITLE
Only 98 songs out of my over 340 songs show up in my library with the 'Songs' layout.

### ISSUE THREAD

**Issue by kane090** [zachomedia/apple-music-webplayer#12]
As the title says.

**Comment by zachomedia** [comment]
@kane090 The songs page loads in 100 song increments. Can you check the console for any errors?

**Comment by zachomedia** [comment]
Can you run the two following commands in the console?:

```javascript
MusicKit.getInstance().api.library.songs(null, { limit: 100 }).then(r => console.log(r.length));
MusicKit.getInstance().api.library.songs(null, { offset: 100, limit: 100 }).then(r => console.log(r.length));
```

**Comment by kane090** [comment]
I ran the commands and this is what I got:

MusicKit.getInstance().api.library.songs(null, { limit: 100 }).then(r => console.log(r.length));
Promise {<pending>}
VM81:1 98
MusicKit.getInstance().api.library.songs(null, { offset: 100, limit: 100 }).then(r => console.log(r.length));
Promise {<pending>}
VM97:1 99

**Comment by zachomedia** [comment]
Can you look at the request to `https://api.music.apple.com/v1/me/library/songs` in the Network tab, and see if there is a `next` value in the response/what the value is?

**Comment by kane090** [comment]
{next: "/v1/me/library/songs?offset=100",…}
data
:
[{id: "i.2P0NDPNtxONpg1", type: "library-songs", href: "/v1/me/library/songs/i.2P0NDPNtxONpg1",…},…]
next
:
"/v1/me/library/songs?offset=100"

**Comment by zachomedia** [comment]
Interesting. Unfortunately, the `next` param doesn't get passed through in the response to my application. I just changed the logic to keep up on increasing the offset until the response contains 0 items. Can you try the songs view now?

**Comment by kane090** [comment]
Just tried the view. Every song shows up! Well done and thank you!

**Comment by zachomedia** [comment]
Great!
