### ISSUE TITLE
Album View - Show Year & Genre

### ISSUE THREAD

**Issue by hcuk94** [zachomedia/apple-music-webplayer#125]
When an album is open to the track listing, there is nowhere that shows the year and genre of the album, as is shown on the equivalent screen in Apple Music.

It'd be great to get this added in - I'm not fussed about genre but I refer to year pretty often when listening to an album.

PS: Excellent work, love the web app and use it all the working day.

**Comment by zachomedia** [comment]
@hcuk94 Thank you for the feature request! The release date and genres are not shown on the Album view page.
