### ISSUE TITLE
music not load

### ISSUE THREAD

**Issue by poentodewo** [zachomedia/apple-music-webplayer#16]
just login as usual music library not loaded

https://screenshotscdn.firefoxusercontent.com/images/2c250f32-84fa-4824-94b5-8e8310265428.png

**Comment by zachomedia** [comment]
Hello @poentodewo,

Did you try clicking something in the sidebar?

**Comment by poentodewo** [comment]
@zachomedia Yes but nothing happen

https://thumbs.gfycat.com/IllustriousThunderousKiwi-size_restricted.gif

**Comment by zachomedia** [comment]
Can you see if there are any errors in the developer console?

**Comment by poentodewo** [comment]
I donk now how to see error
![screenshot at 2018-06-26 19-08-51](https://user-images.githubusercontent.com/15877677/41910687-9c57f39a-7974-11e8-98aa-52400c50dcc9.png)
event not working with safari ios
![image-1](https://user-images.githubusercontent.com/15877677/41911061-cc48f1ac-7975-11e8-9957-c776e6997f12.jpg)

**Comment by KevDoy** [comment]
I do not have an Apple Music subscription but have songs in iTunes, nothing shows up for me either. Is that the issue?

**Comment by zachomedia** [comment]
@KevDoy Yeah, if you don't have an Apple Music subscription, it won't show anything. I want to show a message to this fact, but the flag for this isn't working/is missing right now (I have an open bug with Apple for this).

@poentodewo Do you have an active Apple Music subscription?

**Comment by poentodewo** [comment]
@zachomedia Yes I have
I can play with my phone 
https://gfycat.com/GroundedEarnestBlackmamba

**Comment by zachomedia** [comment]
@poentodewo Can you go to https://music.zacharyseguin.ca/debug and provide me with the output?

**Comment by poentodewo** [comment]
here 
https://gfycat.com/WigglyVictoriousDonkey

**Comment by zachomedia** [comment]
Ok, interesting. I've actually managed to get in that state myself in my local development environment (but only in Safari, not Chrome).

I'm going to experiment a bit and see what I can figure out.

**Comment by zachomedia** [comment]
@poentodewo I just tried a change that seemed to fix it locally for me, can you try now? (You may need to clear caches)

**Comment by poentodewo** [comment]
Thanks its working now 
https://screenshotscdn.firefoxusercontent.com/images/a6ddb4ff-0ede-4cb2-8f94-34c46655a632.png

**Comment by zachomedia** [comment]
Great!
