### ISSUE TITLE
Adding a volume slider...

### ISSUE THREAD

**Issue by kane090** [zachomedia/apple-music-webplayer#17]

**Comment by zachomedia** [comment]
Yeah, a volume slider would be nice. There is no API for setting the volume right now, unfortunately.

**Comment by d0lb33** [comment]
> Yeah, a volume slider would be nice. There is no API for setting the volume right now, unfortunately.

Just set MusicKit.getInstance().player.volume = a number here

It seems to not be mentioned in the documentation, but this works for me. Along with setting the queue to shuffle/repeate. Just to MusicKit.getInstance().player.shuffleMode = 1

Observe here in my console. The values retain the information and you can also observe it in the queue. 

![capture](https://user-images.githubusercontent.com/18106388/47880820-4a1c6880-ddf2-11e8-9d89-85a939253769.PNG)

**Comment by zachomedia** [comment]
This has been implemented in the latest release.
