### ISSUE TITLE
Songs Not Playing

### ISSUE THREAD

**Issue by jmauss** [zachomedia/apple-music-webplayer#18]
Not sure what I am doing wrong here, but when I select a song, it appears at the top of the screen but does not begin playing. Previews of songs would play fine before I logged in (the 30 second clips), but after logging in, no songs play. My playlists and library do show up fine.

**Comment by zachomedia** [comment]
Can you take a look at the console in Developer Tools, and see if there are any errors?

**Comment by jmauss** [comment]
Forgive my ignorance, how exactly do I access the developer tools to see?

**Comment by jmauss** [comment]
Chromium (latest stable) on Arch Linux

**Comment by zachomedia** [comment]
Do you have https://wiki.archlinux.org/index.php/chromium#Widevine_Content_Decryption_Module_plugin setup? 

Apple Music send the content encrypted and needs to be decrypted by the browser.

**Comment by jmauss** [comment]
Ah, I was not aware this was a requirement. Works fine now, thank you.
