### ISSUE TITLE
When clicking next or previous, and that song is not available, it always stays on the same song

### ISSUE THREAD

**Issue by Thoro** [zachomedia/apple-music-webplayer#3]
When clicking next or previous, and that song is not available, it always stays on the same song.

The previous and next buttons should go forward and backwards until a playable song is found.

**Comment by zachomedia** [comment]
Thanks for the report.

I'm going to look at submitting this issue upstream to Apple, since I call the `skipToNextItem` (https://developer.apple.com/documentation/musickitjs/musickit/musickitinstance/2992718-skiptonextitem) function.

**Comment by zachomedia** [comment]
I'll see if there's a workaround at least for now though.

**Comment by Thoro** [comment]
Not really necessary - since it only appears to happen when manually clicking next, the auto play jumper over correctly

**Comment by jaehess** [comment]
@zachomedia Radar number?

**Comment by zachomedia** [comment]
@jaehess It's 41270069
I'm not sure if this is still an issue, as I believe the last time I tried to skip over an unplayable song it worked as expected.

**Comment by jaehess** [comment]
> @jaehess It's 41270069
> I'm not sure if this is still an issue, as I believe the last time I tried to skip over an unplayable song it worked as expected.

This doesn't seem to be reproducing - @Thoro Can you confirm?

**Comment by Thoro** [comment]
I think it's fixed.
