### ISSUE TITLE
Add ability to love/dislike song

### ISSUE THREAD

**Issue by jcsims** [zachomedia/apple-music-webplayer#49]
First: thanks for building this, it's awesome! I'm using it on Linux, and it's super slick.

I tend to love/dislike songs to affect Apple's recommendations, but don't see a way to do that in the webplayer yet. I'm not familiar with Apple's APIs for this, but it _looks_ like it's possible to do this via the API? https://developer.apple.com/documentation/applemusicapi/add_a_personal_song_rating

**Comment by zachomedia** [comment]
@jcsims Thanks for the request. You are correct, it's possible with the API endpoint you found.
