### ISSUE TITLE
No songs play, COR issue

### ISSUE THREAD

**Issue by brianclinkenbeard** [zachomedia/apple-music-webplayer#5]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.itunes.apple.com/WebObjects/MZPlay.woa/wa/widevineCert. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://embed.music.apple.com’).`
Firefox, problem occurs without any add-ons enabled. Apple Music toolbox works fine.

**Comment by zachomedia** [comment]
@brianclinkenbeard Can you try logging out and logging back in? I ran into this once, and I think that solved it.

**Comment by brianclinkenbeard** [comment]
works now, didn't even have to log out.
