### ISSUE TITLE
Can't play music that has been bought by the user

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [zachomedia/apple-music-webplayer#50]
Music that has been purchased by the user will show up in the library listing, but uppon clicking on any song, the following errors are logged in the console:

![image](https://user-images.githubusercontent.com/19349898/45589368-a256e400-b8f2-11e8-8a24-561033619f9c.png)
![image](https://user-images.githubusercontent.com/19349898/45589371-b00c6980-b8f2-11e8-8aa0-632427bffdfe.png)

I'm specifically talking about music that has been purchased, and is not available otherwise. For instance, I'm trying to listen to King Crimson's In the Court of the Crimson King, which is only available throught purchase.

**Comment by jaehess** [comment]
@zachomedia I am tracking this if you want to label as Submitted to Apple.

**Comment by jaehess** [comment]
This should be working now. Please let me know if this is still an issue.

**Comment by PierreOlivierBrillant** [comment]
@jaehess Yes it seems to be working for me.

**Comment by d0lb33** [comment]
@PierreOlivierBrillant Is MusicKitJS down for anyone else right now? @jaehess

**Comment by jaehess** [comment]
Things seem up for me:

https://js-cdn.music.apple.com/musickit/v1/index.html

**Comment by d0lb33** [comment]
@jaehess Try logging into zachs program. Its giving a store front error.

**Comment by d0lb33** [comment]
![image](https://user-images.githubusercontent.com/18106388/48095443-5f223e80-e1da-11e8-880f-45ffe150ec75.png)

**Comment by d0lb33** [comment]
Even the website you linked is giving me a storefront error @jaehess

**Comment by jaehess** [comment]
I am not seeing this issue. The 403 represents an issue with the music user token. If you reset your browser cookies / local storage are you still seeing the issue?

What version are you seeing in the top right corner of the link above?

**Comment by d0lb33** [comment]
@jaehess 1.1.0-15 also I have tried in edge, also tried on a different device and it did not work. Could this be an issue with my account? I cant even sign in to apple music through there toolkit website. Go here and try signing in, does it let you? https://itunes.apple.com/us/album/reset/1440349047?app=music&ign-mpt=uo%3D4

**Comment by d0lb33** [comment]
![image](https://user-images.githubusercontent.com/18106388/48096223-49157d80-e1dc-11e8-90dd-ed01b3ab7396.png)
@jaehess

**Comment by jaehess** [comment]
Reproducing there. Investigating now.

**Comment by d0lb33** [comment]
@jaehess I was able to login too!!! Hmm, still cant seem to login on my personal application.

**Comment by jaehess** [comment]
@d0lb33 a fix is rolling out now.

**Comment by d0lb33** [comment]
@jaehess From Apple?

**Comment by jaehess** [comment]
@d0lb33 Yes.

**Comment by d0lb33** [comment]
@jaehess I am building a musickitjs application right now, I have a few questions that may be bugs or may be my own self. Is there some way I can message you?

**Comment by d0lb33** [comment]
@jaehess For example there are some songs in my library that when set to the queue have no play params. Zachs player doesn't work with them neither does mine. The only way to get the song to play is to delete it from my library and readd it. The weird thing is that if I look at it on my phone, and search it up, it shows as if I have not added the song to my library yet (still has a plus next to it). But when I click the plus, I have two of those songs in my library. It seems to only happen on my library as it is not happening to on eof my friends when trying

**Comment by jaehess** [comment]
@d0lb33 Would you mind posting your questions to the [MusicKit Apple Developer Forums](https://forums.developer.apple.com/community/app-frameworks/musickit)? This will allow us to support your questions and reach a wider audience at Apple.
