### ISSUE TITLE
Empty query results in unexpected error

### ISSUE THREAD

**Issue by PierreOlivierBrillant** [zachomedia/apple-music-webplayer#52]
URL for Library: `https://music.zacharyseguin.ca/library/search?q=`
URL for Apple Music: `https://music.zacharyseguin.ca/search?q=`

The included url results in an "Unexpected error" in the UI, for both for Apple Music, and Library queries.

![image](https://user-images.githubusercontent.com/19349898/45600178-786ef180-b9c6-11e8-88fc-17f6113bbb68.png)
The first error is with Apple Music and the second with the library.

**Comment by zachomedia** [comment]
Thanks for the report. I've fixed the issue with empty search queries.
