### ISSUE TITLE
Select Bitrate

### ISSUE THREAD

**Issue by uvoglu** [zachomedia/apple-music-webplayer#54]
Great tool you are creating, congratulations!

One thing I noticed though is that the songs are only streamed at a low bitrate (64kbps). The Music Kit JS API allows you to select between 64kbps (normal quality) and 256kbps (high quality) (https://developer.apple.com/documentation/musickitjs/musickit/playbackbitrate)

Is it possible to switch to better quality?

Thanks and keep up the good work!! :)

**Comment by zachomedia** [comment]
@jaehess Is this actually available yet? The Enumeration doesn't appear to exist.

**Comment by jaehess** [comment]
It is available, but it looks like the enumeration is not actually being exported. I will get this into the next  release. Until then you are welcome to use the enumeration values directly.

**Comment by jaehess** [comment]
This should be available now: `MusicKit.PlaybackBitrate`

**Comment by zachomedia** [comment]
Thanks @jaehess 

@uvoglu This has been added to https://music.zacharyseguin.ca/settings, where you can toggle the bitrate.

**Comment by uvoglu** [comment]
I just tested it and it seems to work :) Thank you!!
