### ISSUE TITLE
Keep playlist / song when i change settings 

### ISSUE THREAD

**Issue by T3kstiil3** [zachomedia/apple-music-webplayer#56]
When i change my settings, player reset current playing song.
I'll be cool if current song whould be keeping 😊

PS: thx for your work. Just a awesome idea 👍 ! I'll make PR soon for features and bugs fixed !

**Comment by zachomedia** [comment]
Thanks for the report. What browser and OS are you experiencing this in? I was unable to reproduce in Safari and Chrome on macOS.

**Comment by T3kstiil3** [comment]
It's a know bug when you change Bitrate (Changing the bitrate will cause the page to reload.)
Keep sound in localstorage or somethink like this will be cool :)

**Comment by zachomedia** [comment]
Yeah, changing the bitrate currently triggers a full reload because the bitrate setting is only writable when calling `MusicKit.configure`.

**Comment by zachomedia** [comment]
I will look at saving current playlist + song in localstorage.

**Comment by T3kstiil3** [comment]
It was my first idea 👍

**Comment by jaehess** [comment]
@zachomedia FWIW documentation is lacking for bitrate. You can set the bitrate without reloading, but it will not take effect until the next track is started.

```
MusicKit.getInstance().bitrate = MusicKit.PlaybackBitrate.HIGH
```

**Comment by zachomedia** [comment]
Thanks @jaehess. I'll update it then to change that value.

Just note, the docs do say that's a `readonly` value (https://developer.apple.com/documentation/musickitjs/musickit/musickitinstance/2992702-bitrate).
