### ISSUE TITLE
Design mockups?

### ISSUE THREAD

**Issue by cunidev** [zachomedia/apple-music-webplayer#60]
As the app is currently slightly messy, it might be useful to start accepting simple design mockups. If you do, I can try to contribute myself.

**Comment by zachomedia** [comment]
I'm open to anyone contributing design mockups.

**Comment by cunidev** [comment]
Great, thanks!

**Comment by cunidev** [comment]
A few ideas to begin with

![first-mockup-top](https://user-images.githubusercontent.com/13885615/48895707-07c0d700-ee46-11e8-8a20-cdbae2d6a570.png)
---
![first-mockup-bottom](https://user-images.githubusercontent.com/13885615/48895706-07c0d700-ee46-11e8-932d-afefa228a02c.png)

**Comment by zachomedia** [comment]
Thank you for the mockup.
I'm currently working on a redesign of the app and will incorporate your feedback. I will share a preview soon (in the next couple of weeks).

**Comment by zachomedia** [comment]
@cunidev I've started working on it, here's a preview: https://musictest.zacharyseguin.ca. Feedback is welcome.

I'm experimenting with removing the sidebar and instead putting links along to top to give more room for content, and this addresses most of the feedback in your mockup.
