### ISSUE TITLE
you should add shuffle

### ISSUE THREAD

**Issue by dickassbutt69** [zachomedia/apple-music-webplayer#62]
its not exactly a huge issue or anything but shuffle would be nice to have. i havent really toyed around with the web player to see its full potential and capabilities, but im very truly impressed with what youve managed to do thus far! keep up the good work man.
(also if there already is a shuffle feature that im being ignorant to, please let me know)

**Comment by zachomedia** [comment]
Thank you!

Regarding shuffle - at the time I built this, it wasn't ready for use. I will have to check again and see if it's been implemented within MusicKit JS. There is a temporary "shuffle" feature for albums/playlists at the top called "Shuffle All". (See #7 for more info)
