### ISSUE TITLE
Generating a playlist artwork with Canvas

### ISSUE THREAD

**Issue by n3oney** [zachomedia/apple-music-webplayer#66]
So, you probably already noticed that if you don't give a photo for a playlists, in the Apple Music app (on iPhones) it generates one with four first songs' artworks in a 2x2 grid. That can easily be done using the HTML5 Canvas. I would appreciate if you added that option.

**Comment by n3oney** [comment]
I think i'm able to do that and do a pull request, if only i knew where does the songs array come from and if it is available on the SongCollectionItem.vue

**Comment by zachomedia** [comment]
It doesn't look like the songs array is available in SongCollectionItem. You would have to make a separate API request to get them, which the call would be similar to https://github.com/zachomedia/apple-music-webplayer/blob/master/src/views/SongCollection.vue#L143 .

If you have issues getting it to work, I will probably have some time during the upcoming holidays to get the tracks loading for you.
