### ISSUE TITLE
Bug artist page

### ISSUE THREAD

**Issue by T3kstiil3** [zachomedia/apple-music-webplayer#74]
We can't display artist page  :
https://music.zacharyseguin.ca/artists/1383397733

This is a recent bug, not present before.

**Comment by zachomedia** [comment]
Thanks for the report. Looks like Apple changed how MusicKit JS makes the API call when you ask for the artists and it's albums. 

I'll try to have a fix shortly.

**Comment by zachomedia** [comment]
I've pushed a fix.

**Comment by T3kstiil3** [comment]
Thx 😄
