### ISSUE TITLE
Unable to play any music

### ISSUE THREAD

**Issue by FurkanToprak** [zachomedia/apple-music-webplayer#76]
Attempting to play anything on Chromium browsers brings up multiple `Media Playback Error: An error occurred during media playback.` per playlist I press play on and also one `Unexpected Error: An unexpected error occurred.` per song I attempt to play.

**Comment by Datsuke** [comment]
Same problem here, I been using the app on Chrome for a few days now and it just stopped working, I tried another PC other browsers and re-authorizing the app to my Apple ID however none of these work, the only thing that happens is that it ''loads'' the song forever but not even the gray loading bar appears

**Comment by zachomedia** [comment]
Thanks for the report @FurkanToprak and @Datsuke.

I just tested myself on Safari and Chrome on my Mac, and I don't have any issues. Can you provide some additional information:

- Operating system
- Country
- Do song previews work when logged out?
- Do you have the same issue with https://tools.applemusic.com/? There's a signin button when you open up a library or playlist 
- Are there are any errors in the Developer Tools console?

**Comment by Datsuke** [comment]
Windows 10 1809 on build 17763.316
Apple ID is from Mexico however connection is made through a VPN connected to the US
Google Chrome Version 72.0
Same issue with song previews
No issues while playing media through tools.applemusic

`ncaught (in promise) UNKNOWN_ERROR: UNKNOWN_ERROR
    at Function.MKError.serverError (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:25749)
    at EncryptedSession.KeySession._handleLicenseResponse (https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:104916)
    at https://js-cdn.music.apple.com/musickit/v1/musickit.js:1:103100
MKError @ musickit.js:1
MKError.serverError @ musickit.js:1
KeySession._handleLicenseResponse @ musickit.js:1
(anonymous) @ musickit.js:1
Promise.then (async)
KeySession.startLicenseSession @ musickit.js:1
t @ raven.js:376`

this is all I get after clearing the console and making a request

**Comment by zachomedia** [comment]
Are you able to look at the network tab and see if there are requests failing? Looks like something is failing with MusicKit JS when it get the keys for the encrypted media session (cc/ @jaehess)

**Comment by msjyoo** [comment]
Same issue here!

**Comment by msjyoo** [comment]
I found a fix, deleting all localStorage data seems to have fixed it for me. I've been using this since it was launched so there may have been some old date there.

**Comment by zachomedia** [comment]
Thanks for sharing @msjyoo 

@Datsuke can you try clearing all the local storage and seeing if it resolves the issue for you too?

**Comment by Datsuke** [comment]
@zachomedia It worked! once I deleted local storage and restarted Windows it worked again

thanks for replying our questions!

**Comment by FurkanToprak** [comment]
> Thanks for sharing @msjyoo
> 
> @Datsuke, @FurkanToprak can you try clearing all the local storage and seeing if it resolves the issue for you too?

Thanks for the report @FurkanToprak and @Datsuke.

I just tested myself on Safari and Chrome on my Mac, and I don't have any issues. Can you provide some additional information:


Ubuntu 18.04
USA
Chromium Version 72.0.3626.121 (Official Build) snap (64-bit) (Worked on Firefox)
Everything except for playing worked.
No problems at tools.applemusic.com
No.

I couldn't fix it by reloading and ignoring cache content (shift + Reload) or by signing into different users. I'm not willing to clear local data, but that should be irrelevant as there should be a server-side fix to this ideally. I'm willing to give more info/collaborate as needed.

**Comment by msjyoo** [comment]
@FurkanToprak To clear localStorage data, you open DevTools on the website, and go to Stroage, right-click local storage tab, and select "Delete All".

It won't clear data for any of your other websites, and all Apple Music data would be stored with Apple anyway.

**Comment by FurkanToprak** [comment]
@msjyoo Yeah, I did that (and know that). Still hasn't worked for me.

**Comment by zachomedia** [comment]
@FurkanToprak Is this still an issue?

**Comment by FurkanToprak** [comment]
@zachomedia Yes. When I click on a song, album art, song title, etc. all changes correctly but `Unexpected Error: An unexpected error occurred.` occurs. Media playback error no longer occurs.

**Comment by EkanshdeepGupta** [comment]
Hi. I am having a similar issue. The site works great on Firefox, but not on Chromium.

Problem:
When I access the website from Chromium, I get the message telling me to 'install or enable Encrypted Media Extensions in your browser'.
After this, playing any media throws: Media Playback Error: An error occurred during media playback.

What I've tried:
 As far as I could tell, EME is already enabled in Chromium by default, and I could not find any way to enable or install it.
I have ensured that the setting for Protected Content (in Settings > Advanced > Content Settings > Protected Content) is already enabled, and I have already cleared all browsing data and restored settings to default. No dice.

Thank you so much. If you know how to enable EME in Chromium, or fix this error, please let me know.  Till then, I'll continue using this service in Firefox.

Some diagnostic information:
OS: Fedora 30 KDE
Chromium: Version 73.0.3683.86 (Developer Build) Fedora Project (64-bit)

Please let me know if there is any more information I can provide to help.

Might I just add, this is a great service and I really appreciate the work you've done!

**Comment by zachomedia** [comment]
@EkanshdeepGupta Chromium (the open source version of Chrome) does not have the encrypted media extensions included. I'm not sure how to obtain it on Fedora, but you'll be looking for the widevine package.

**Comment by EkanshdeepGupta** [comment]
Oh. I did not know that. Thanks a lot, I will look if there is a way to do this and update accordingly (hopefully).

**Comment by FurkanToprak** [comment]
Works on firefox but not chromium. Issue closed.

**Comment by c-hild** [comment]
Had the same issue, also on current Chromium on current arch linux, this was the console content:

Error with Feature-Policy header: Unrecognized feature: 'notifications'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'push'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'document-write'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'image-compression'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'legacy-image-formats'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'max-downscaling-image'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'unsized-media'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'vertical-scroll'.
for-you:1 Error with Feature-Policy header: Unrecognized feature: 'animations'.
for-you:1 Uncaught (in promise) DOMException
console.js:35 PLAYBACK_ERROR DOMException
t.<computed> @ console.js:35

will checkout https://aur.archlinux.org/packages/chromium-widevine/ as a solution, hopefully others with the same error will find this the way I did.
