### ISSUE TITLE
Synching Issues When Song Changed

### ISSUE THREAD

**Issue by FurkanToprak** [zachomedia/apple-music-webplayer#82]
When I switch between songs by clicking on a new song, the title and album cover of the song doesn't update. Below is a screenshot of the song title being incorrect. Actually playing was the song "The 1975", but the shown title is the title of the previous song.
![image](https://user-images.githubusercontent.com/46634307/57125474-30cb8900-6d4f-11e9-839b-3789614c6e30.png)

**Comment by zachomedia** [comment]
Thanks for the report. This may be related to #78, but I'll have to check more to confirm.

**Comment by FurkanToprak** [comment]
I believe both bugs are indeed caused by an upstream error, but I don't think the temporary fix you've applied fixed it.

**Comment by zachomedia** [comment]
@FurkanToprak Is this issue still occurring? I cannot seem to reproduce it myself.

If it is still occurring, can you provide me with a few more details?:

- Does this happen all the time or just occasionally? Does it happen just on the Library Songs page or any page with a song list (album/playlist/etc.)?
- Are there any error messages around the time the problem happens?
- Does it happen in different browsers?

**Comment by FurkanToprak** [comment]
@zachomedia So I'm unable to reproduce this error, so I believe it is fixed. I tried skipping songs, clicking on a new song, letting a song end and transition to the next song naturally, clicking on playlists; all of this was tried on shuffle and regular mode. However, I still do get the notification "Unexpected Error: An unexpected error occurred." whenever I first get on https://music.zacharyseguin.ca/library/songs and click on a song. If I click on a playlist and then return to my songs library, however, this issue is fixed.

I only use Firefox 66.0.5 (64-bit) for Ubuntu for this website.
