### ISSUE TITLE
Option to bring back the old UI layout.

### ISSUE THREAD

**Issue by LeonCupac** [zachomedia/apple-music-webplayer#88]
Can you make it an option in the settings menu where you can turn on the old UI. (playapplemusic.com) I really liked it and it was the reason i chose your site over something else. (musi.sh or maevemusic.app) :D

**Comment by zachomedia** [comment]
Hello, @LeonCupac, playapsplemusic.com is a separate project by a different developer than this one. You can find the project at https://github.com/naveedgol/music-web-player and can access it on the web at https://naveedgol.github.io/music-web-player/ .
