### ISSUE TITLE
Enhancement: option to disable localization

### ISSUE THREAD

**Issue by vladasbarisas** [zachomedia/apple-music-webplayer#92]
I'd like to have an option to disable localization based on the account's country. I have a russian Apple Music account and I'd like to be able to view the US top charts, without russian translations for playlist and artist names and without music added by local music curators. Do you think this would be possible?

I can try adding this myself, but I'm not sure where to start.

**Comment by zachomedia** [comment]
Thank you for the request. This might be possible as there does appear to be some "storefrontid" settings but I'm not 100% positive. I can do more research/trial to see if this is something that can be done.

**Comment by vladasbarisas** [comment]
There's a local storage item with a long alphanumeric name that ends with ".s", and it seems like it affects the Top Charts tab and artist name translations. Changing it to "gb" allowed me to view the UK charts without russian translations, but it didn't affect the For You or Library tabs.

storefrontid seems promising, I'll try playing with it over the weekend.

**Comment by zachomedia** [comment]
@vladasbarisas This feature has now been implemented. Please note, though, that it doesn't appear to have any effect on the For You or library sections (those always use your storefront). But you can at least now view playlists and albums from other countries.
